services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    volumes:
      - mongodata:/data/db
    networks: [backend]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 12

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    depends_on: [mongo]
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/${MONGODB_DB}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASS}
      ME_CONFIG_SITE_BASEURL: /db
    networks: [backend]
    expose: ["8081"]

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: server
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 4000
      # Provide BOTH env names (your code reads either in different places)
      MONGODB_URI: mongodb://mongo:27017/${MONGODB_DB}
      MONGO_URI:   mongodb://mongo:27017/${MONGODB_DB}
      JWT_SECRET: ${JWT_SECRET}
      NODE_OPTIONS: --experimental-specifier-resolution=node
    networks: [backend]
    expose: ["4000"]

  proxy:
    image: nginx:1.25-alpine
    container_name: proxy
    depends_on: [server, mongo-express]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - /dev/null:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks: [frontend, backend]

volumes:
  mongodata:

networks:
  frontend: {}
  backend: {}
