apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-ingress
  namespace: mern
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"   # set true after TLS works
spec:
  rules:
    - http:
        paths:
          - path: /            # React app + static /dist
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 4000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 4000
          - path: /db
            pathType: Prefix
            backend:
              service:
                name: mongo-express
                port:
                  number: 8081
